name: simple_telephony
description: "Telephony bridge for Unify Messages+"
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.simplezen.simple_telecom
        pluginClass: SimpleTelecomPlugin
