name: simple_telephony_platform_interface
description: >-
  A common platform interface for the simple_telephony_native plugin.
version: 0.2.1
homepage: https://www.simplezen.io/development

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
